

const db = require('../db/connection')
const Recipe = require('../models/recipe')
const Comment = require('../models/Comments')


db.on('error', console.error.bind(console, 'MongoDB connection error:'))

const main = async () => {
  await Recipe.deleteMany()
  await Comment.deleteMany()
  const comment1 = {
    "name": "plankton",
    "comment": "this krabby patty is great!",
    "starRating": 5
  }

  const comment = await Comment.create(comment1)

  const recipes = [
    {
      "dishName": "Maple Salmon",
      "imgUrl": "https://images.unsplash.com/photo-1556845752-92f6fe9f596d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=600&q=60",
      "starRating": 2,
      "briefDescription": "This is the best and most delicious salmon recipe, and very easy to prepare. I love maple in everything and put this together one night. My husband totally loved it; he did not like salmon that much until he had this",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Salmon",
        "twoAmount": "2",
        "twoUnit": "Oz",
        "twoName": "Garlic",
        "threeAmount": "4",
        "threeUnit": "Tsp",
        "threeName": "Lemon Juice",
        "fourAmount": "1/2",
        "fourUnit": "Tsp",
        "fourName": "Salt",
        "fiveAmount": "3",
        "fiveUnit": "Tbsp",
        "fiveName": "Maple",
        "sixAmount": "1",
        "sixUnit": "Tsp",
        "sixName": "Soy Sauce"
      }],
      "instructions": [{
        "stepOne": "In a small bowl, mix the maple syrup, soy sauce, garlic, garlic salt, and pepper.",
        "stepTwo": "Place salmon in a shallow glass baking dish, and coat with the maple syrup mixture. Cover the dish, and marinate salmon in the refrigerator 30 minutes, turning once.",
        "stepThree": "Preheat oven to 400 degrees F (200 degrees C).",
        "stepFour": "Place the baking dish in the preheated oven, and bake salmon uncovered 20 minutes, or until easily flaked with a fork."
      }],
      "prepTime": "30 minutes",
      "comments": comment._id

    },
    {
      "dishName": "Baked Cod",
      "imgUrl": "https://images.unsplash.com/photo-1587913956756-4fcf4833241d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=600&q=60",
      "starRating": 4,
      "briefDescription": "Cod fillets marinated in rich blend of spices and then baked",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Cod",
        "twoAmount": "3",
        "twoUnit": "Cups",
        "twoName": "Non-fat Yogurt",
        "threeAmount": "16",
        "threeUnit": "Fl-Oz",
        "threeName": "Pureed Tomatoes",
        "fourAmount": "1",
        "fourUnit": "Tsp",
        "fourName": "Salt",
        "fiveAmount": "3",
        "fiveUnit": "Tbsp",
        "fiveName": "White Vinegar",
        "sixAmount": "2",
        "sixUnit": "Tbsp",
        "sixName": "Lemon Juice"
      }],
      "instructions": [{
        "stepOne": "Preheat oven to 400 degrees F (200 degrees C).",
        "stepTwo": "Coat both sides of cod in melted butter in the baking dish.",
        "stepThree": "Bake cod in the preheated oven for 10 minutes. Remove from oven; top with lemon juice, wine, and cracker mixture. Place back in oven and bake until fish is opaque and flakes easily with a fork, about 10 more minutes",
        "stepFour": "Garnish baked cod with parsley and green onion. Serve with lemon wedges."
      }],
      "prepTime": "40 minutes"
    },
    {
      "dishName": "Blackened Tuna",
      "imgUrl": "https://images.unsplash.com/photo-1530260626688-048279320445?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=600&q=60",
      "starRating": 5,
      "briefDescription": "It may seem simple, but it's my favorite way to have tuna. Seared fish steaks are a Cajun tradition",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Tuna",
        "twoAmount": "2",
        "twoUnit": "Tsp",
        "twoName": "Cajun Seasoning",
        "threeAmount": "1",
        "threeUnit": " ",
        "threeName": "Lemon",
        "fourAmount": "2",
        "fourUnit": "Tsp",
        "fourName": "Salt",
        "fiveAmount": "1",
        "fiveUnit": "Tbsp",
        "fiveName": "Butter",
        "sixAmount": "3",
        "sixUnit": "Tbsp",
        "sixName": "Olive Oil"
      }],
      "instructions": [{
        "stepOne": "Generously coat tuna with Cajun seasoning.",
        "stepTwo": "Heat oil and butter in a large skillet over high heat. ",
        "stepThree": "When oil is nearly smoking, place steaks in pan. ",
        "stepFour": "Cook on one side for 3 to 4 minutes, or until blackened. Turn steaks, and cook for 3 to 4 minutes, or to desired doneness."
      }],
      "prepTime": "15 minutes"
    },
    {
      "dishName": "Fish Tacos",
      "imgUrl": "https://images.unsplash.com/photo-1512838243191-e81e8f66f1fd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=600&q=60",
      "starRating": 4,
      "briefDescription": "I'm from San Diego and these taste just like home! We live in the south now, and nobody has heard of these! Serve with homemade pico de gallo, and lime wedges to squeeze on top!",
      "ingredients":
        [{
          "oneAmount": "1",
          "oneUnit": "Lbs",
          "oneName": "Tilapia",
          "twoAmount": "2",
          "twoUnit": " ",
          "twoName": "Whole Peppers",
          "threeAmount": "1",
          "threeUnit": " ",
          "threeName": "Egg",
          "fourAmount": "4",
          "fourUnit": " ",
          "fourName": "Flour Tortillas",
          "fiveAmount": "4",
          "fiveUnit": "Tbsp",
          "fiveName": "Butter",
          "sixAmount": "6",
          "sixUnit": "Tbsp",
          "sixName": "Olive Oil"
        }],
      "instructions": [{
        "stepOne": "Mix sour cream and lime juice together in a large bowl; season with salt and black pepper. Reserve about half the mixture in another bowl for serving. Mince half the jalapeno pepper; save other half for later. Toss cabbage, green onions, and minced jalapeno half in remaining sour cream mixture until slaw is well mixed.",
        "stepTwo": "Heat olive oil and remaining jalapeno half in a large skillet over medium heat; swirl oil to coat skillet evenly. Season tilapia fillets with salt and pepper.",
        "stepThree": "Heat tortillas in the microwave on high until warm, 20 to 30 seconds.",
        "stepFour": "Serve fish in warmed tortillas topped with cabbage slaw, reserved sour cream mixture, and cilantro"
      }],
      "prepTime": "35 minutes"
    },
    {
      "dishName": "Mahi Mahi",
      "imgUrl": "https://images.unsplash.com/photo-1579631542761-d7c4e913f8d4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
      "starRating": 5,
      "briefDescription": "This fish has a sweet and spicy flavor that goes well with buttered rice.",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Mahi Mahi",
        "twoAmount": "1/2",
        "twoUnit": "Tsp",
        "twoName": "Garlic Powder",
        "threeAmount": "1",
        "threeUnit": "Tbsp",
        "threeName": "Soy Sauce",
        "fourAmount": "1",
        "fourUnit": "Tsp",
        "fourName": "Balsamic Vinegar",
        "fiveAmount": "2",
        "fiveUnit": " ",
        "fiveName": "Garlic Cloves",
        "sixAmount": "6",
        "sixUnit": "Tbsp",
        "sixName": "Olive Oil",
        "sevenAmount": "1",
        "sevenUnit": "Cup",
        "sevenName": "Gordon's Marinade"
      }],
      "instructions": [{
        "stepOne": "In a shallow glass dish, stir together the honey, soy sauce, balsamic vinegar, ginger, garlic and olive oil. Season fish fillets with salt and pepper, and place them into the dish. ",
        "stepTwo": "Heat vegetable oil in a large skillet over medium-high heat. Remove fish from the dish, and reserve marinade. Fry fish for 4 to 6 minutes on each side, turning only once, until fish flakes easily with a fork. Remove fillets to a serving platter and keep warm.",
        "stepThree": "Pour reserved marinade into the skillet, and heat over medium heat until the mixture reduces to a glaze consistently.",
        "stepFour": " Spoon glaze over fish, and serve immediately."
      }],
      "prepTime": "45 minutes"
    },
    {
      "dishName": "Vegetarian Chili",
      "imgUrl": "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
      "starRating": 3,
      "briefDescription": "Break out your soup pot and fix up a batch of this delicious, spicy vegetarian chili today! It's ready in no time, and packed with vegetables, beans - and flavor!",
      "ingredients": [{
        "one": "1 Cup Drained Kidney Beans",
        "two": "1/2 Cup Crushed Tomatoes",
        "three": "1 Lb Bell Peppers",
        "four": "1 Tsp Olive Oil",
        "five": "2 Cups Corn",
        "six": "1/4 Lb Ginger",
        "oneAmount": "1",
        "oneUnit": "Cup",
        "oneName": "Drained Kidney Beans",
        "twoAmount": "1/2",
        "twoUnit": "Cup",
        "twoName": "Crushed Tomatoes",
        "threeAmount": "1",
        "threeUnit": "Lbs",
        "threeName": "Bell Peppers",
        "fourAmount": "1",
        "fourUnit": "Tsp",
        "fourName": "Olive Oil",
        "fiveAmount": "2",
        "fiveUnit": "Cups",
        "fiveName": "Corn",
        "sixAmount": "1/4",
        "sixUnit": "Lbs",
        "sixName": "Ginger"
      }],
      "instructions": [{
        "stepOne": "Heat the olive oil in a large pot over medium heat. Stir in the onion, and season with bay leaves, cumin, oregano, and salt.",
        "stepTwo": "Cook and stir until onion is tender, then mix in the celery, green bell peppers, jalapeno peppers, garlic, and green chile peppers. When vegetables are heated through, mix in the vegetarian burger crumbles. Reduce heat to low, cover pot, and simmer 5 minutes",
        "stepThree": "Mix the tomatoes into the pot. Season chili with chili powder and pepper. Stir in the kidney beans, garbanzo beans, and black beans.",
        "stepFour": "  Bring to a boil, reduce heat to low, and simmer 45 minutes. Stir in the corn, and continue cooking 5 minutes before serving."
      }],
      "prepTime": "55 minutes"
    },
    {
      "dishName": "Avocado and Tuna Tapas ",
      "imgUrl": "https://images.unsplash.com/photo-1529268127899-36bf4524c254?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80",
      "starRating": 4,
      "briefDescription": "This is a light, healthy tapas that goes best with crisp white wines and crunchy bread. This recipe is great for experimenting with a variety of different vegetables, spices, and vinegars",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Can",
        "oneName": "White Tuna",
        "twoAmount": "3",
        "twoUnit": " ",
        "twoName": "Green Onions",
        "threeAmount": "1/2",
        "threeUnit": "Lbs",
        "threeName": "Bell Peppers",
        "fourAmount": "1",
        "fourUnit": "Tsp",
        "fourName": "Balsamic Vinegar",
        "fiveAmount": "2",
        "fiveUnit": "Tsp",
        "fiveName": "Black Pepper",
        "sixAmount": "2",
        "sixUnit": " ",
        "sixName": "Avocado's"
      }],
      "instructions": [{
        "stepOne": "Stir together tuna, mayonnaise, green onions, red pepper, and balsamic vinegar in a bowl.",
        "stepTwo": "Season with pepper and garlic salt.",
        "stepThree": "Then pack the avocado halves with the tuna mixture.",
        "stepFour": "Garnish with reserved green onions and a dash of black pepper before serving."
      }],
      "prepTime": "23 minutes"
    },
    {
      "dishName": "Kale Soup",
      "imgUrl": "https://images.unsplash.com/photo-1490731678285-2e5640f5a918?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
      "starRating": 2,
      "briefDescription": "This wonderful soup will warm your insides, delight your taste buds, and fill your stomach on a cold winter's night. It is full of dark green kale, potatoes, and cannellini beans.",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Can",
        "oneName": "Cannellini",
        "twoAmount": "1",
        "twoUnit": " ",
        "twoName": "Yellow Onion",
        "threeAmount": "1/2",
        "threeUnit": "Lbs",
        "threeName": "Kale",
        "fourAmount": "2",
        "fourUnit": "Lbs",
        "fourName": "White Potatoes",
        "fiveAmount": "2",
        "fiveUnit": "Tsp",
        "fiveName": "Dried Parsley",
        "sixAmount": "1",
        "sixUnit": "Tbsp",
        "sixName": "Black Pepper",
        "sevenAmount": "1",
        "sevenUnit": "Tbsp",
        "sevenName": "Italian Seasoning"
      }],
      "instructions": [{
        "stepOne": "Heat the olive oil in a large soup pot; cook the onion and garlic until soft. Stir in the kale and cook until wilted, about 2 minutes.",
        "stepTwo": " Stir in the water, vegetable bouillon, tomatoes, potatoes, beans, Italian seasoning, and parsley. ",
        "stepThree": "Simmer soup on medium heat for 25 minutes, or until potatoes are cooked through. ",
        "stepFour": "Season with salt and pepper to taste."
      }],
      "prepTime": "25 minutes"
    },
    {
      "dishName": "Vegetarian Quesadillas",
      "imgUrl": "https://images.unsplash.com/photo-1573010288252-e958ff11effc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
      "starRating": 5,
      "briefDescription": "My vegetarian husband goes crazy over these every time! They are really cheesy, a little bit spicy, and a little bit sweet. Feel free to play around and add chicken or veggies, if you desire. Don't forget the salsa and sour cream!",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Yellow Squash",
        "twoAmount": "1/2",
        "twoUnit": "Lbs",
        "twoName": "Red Onion",
        "threeAmount": "1/2",
        "threeUnit": "Lbs",
        "threeName": "Zucchini",
        "fourAmount": "4",
        "fourUnit": " ",
        "fourName": "Whole Wheat Tortillas",
        "fiveAmount": "1",
        "fiveUnit": "Tsp",
        "fiveName": "Low-Fat Cheese",
        "sixAmount": "1",
        "sixUnit": "Tsp",
        "sixName": "Olive Oil",
        "sevenAmount": "1",
        "sevenUnit": "Can",
        "sevenName": "Black Beans"
      }],
      "instructions": [{
        "stepOne": "In a large nonstick pan, cook red pepper, zucchini, yellow squash, onion, and mushrooms in olive oil over medium to medium-high heat for about 7 minutes, or until just tender.",
        "stepTwo": "Coat the same pan with cooking spray, and place one tortilla in pan. Sprinkle 1/4 cup of cheese evenly over tortilla, and layer 3/4 cup of the vegetable mixture over the cheese.",
        "stepThree": "Sprinkle another 1/8 cup of cheese on the vegetables, and top with a second tortilla. Cook until golden on both sides, for approximately 2 to 3 minutes per side.",
        "stepFour": "Remove quesadilla from pan, and repeat with remaining ingredients. Cut each quesadilla into 8 triangles with a pizza cutter. Serve hot."
      }],
      "prepTime": "35 minutes"
    },
    {
      "dishName": "Vegetarian Wrap",
      "imgUrl": "https://images.unsplash.com/photo-1542128722-d6fe34923abc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
      "starRating": 4,
      "briefDescription": "These are perfect for a hot day. Eat them for lunch, dinner, or snacks, depending on your dietary needs. Add veggies, swap veggies, or add seasoned rice or quinoa for a more filling wrap. Great to make for parties, as they are easy to make, portable and require no immediate refrigeration.",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": " ",
        "oneName": "Avocado",
        "twoAmount": "1",
        "twoUnit": " ",
        "twoName": "Cucumber",
        "threeAmount": "1/2",
        "threeUnit": "Lbs",
        "threeName": "Spinach",
        "fourAmount": "4",
        "fourUnit": " ",
        "fourName": "Whole Wheat Tortillas",
        "fiveAmount": "2",
        "fiveUnit": " ",
        "fiveName": "Tomatoes",
        "sixAmount": "1",
        "sixUnit": "Tsp",
        "sixName": "Olive Oil",
        "sevenAmount": "1",
        "sevenUnit": "Tbsp",
        "sevenName": "Hummus"
      }],
      "instructions": [{
        "stepOne": "Spread the hummus on the bottom 1/3 of the wrap, about 1/2 inch from the bottom edge but spreading out the the side edges",
        "stepTwo": "Layer the cucumber, spinach leaves, tomato slices, avocado.",
        "stepThree": "Fold the wrap tightly, as you would a burrito, tucking in all of the veggies with the first roll then rolling firmly to the end. ",
        "stepFour": "Cut in half and enjoy."
      }],
      "prepTime": "15 minutes"
    },
    {
      "dishName": "Vegetarian Quiche",
      "imgUrl": "https://images.unsplash.com/photo-1518133683791-0b9de5a055f0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
      "starRating": 5,
      "briefDescription": "This is an easy mix-it-up-in-one-bowl-and-cook recipe. I make it for every brunch I attend. You may substitute chopped spinach for the broccoli if you wish.",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Flour",
        "twoAmount": "1",
        "twoUnit": " ",
        "twoName": "Zucchini",
        "threeAmount": "1/2",
        "threeUnit": "Lbs",
        "threeName": "Green Bell Peppers",
        "fourAmount": "1/4",
        "fourUnit": "Lbs",
        "fourName": "Mushrooms",
        "fiveAmount": "1/2",
        "fiveUnit": "Cup",
        "fiveName": "Milk",
        "sixAmount": "1",
        "sixUnit": " ",
        "sixName": "Onion",
        "sevenAmount": "1",
        "sevenUnit": "Tbsp",
        "sevenName": "Salt",
        "eightAmount": "2",
        "eightUnit": "Tbsp",
        "eightName": "Black Peppers"
      }],
      "instructions": [{
        "stepOne": "Bake pie crust in preheated oven until firm, about 8 minutes. Remove crust from oven and set aside. Reduce oven heat to 350 degrees F (175 degrees C.",
        "stepTwo": "Spread 1 cup Colby-Monterey Jack cheese in the bottom of pie crust. Layer vegetable mixture over the cheese and top with the tomatoes. Pour egg mixture into pie shell. Sprinkle remaining 1/2 cup cheese atop the quiche.",
        "stepThree": "Heat olive oil in a large skillet over medium heat. Cook and stir onion, green bell pepper, mushrooms, and zucchini in hot oil until soft, 5 to 7 minutes. Remove vegetables from skillet and set aside.",
        "stepFour": "Bake in preheated oven until a knife inserted near the center comes out clean, 40 to 45 minutes. Cool 5 minutes before serving."
      }],
      "prepTime": "35 minutes"
    },
    {
      "dishName": "Garlic Butter Steak Bites",
      "imgUrl": 'https://www.jocooks.com/wp-content/uploads/2018/10/garlic-butter-steak-bites-1-2.jpg',
      "starRating": 5,
      "briefDescription": "These seared steak bites are cubes of sirloin steak cooked to perfection in a garlic butter sauce. An easy meal or party snack that’s ready in just minutes!",
      "ingredients": [{
        "oneAmount": "4",
        "oneUnit": " ",
        "oneName": "Cloves",
        "twoAmount": "1/2",
        "twoUnit": "Tsp",
        "twoName": "Black Pepper",
        "threeAmount": "1/4",
        "threeUnit": "Cup",
        "threeName": "Parsley",
        "fourAmount": "2",
        "fourUnit": "Lbs",
        "fourName": "New York Strip Steak",
        "fiveAmount": "1/2",
        "fiveUnit": "Tsp",
        "fiveName": "Salt",
        "sixAmount": "8",
        "sixUnit": "Tbsp",
        "sixName": "Butter"
      }],
      "instructions": [{
        "stepOne": 'Mince 4 garlic cloves. Transfer to a bowl and add 1/2 teaspoon freshly ground black pepper. Chop until you have 1/4 cup fresh parsley leaves, then transfer to a small bowl.',
        "stepTwo": 'Cut 2 pounds New York strip steak into 1-inch cubes, then season it with 1/2 teaspoon kosher salt.',
        "stepThree": 'Melt 8 tablespoons (1 stick) unsalted butter in a large skillet over medium high-heat. Add the steak cubes and sear until browned, flipping them halfway through, 6 to 8 minutes total.',
        "stepFour": 'Add the garlic and pepper and cook for 1 minute more. Remove from the heat and garnish with the parsley.'
      }],
      "prepTime": '25 minutes'
    },
    {
      "dishName": 'Sirloin Steak Sandwiches',
      "imgUrl": 'https://s23991.pcdn.co/wp-content/uploads/fly-images/97617/jamie-oliver-steak-sandwiches-recipe-400x300-c.jpg',
      "starRating": 5,
      "briefDescription": "This is a delicious and easy sandwich that gets rave reviews from my husband and brother. The garlic mayo is both easy and delicious.",
      "ingredients": [{
        "oneAmount": "1/4",
        "oneUnit": "Cup",
        "oneName": "Mayonnaise",
        "twoAmount": "1/2",
        "twoUnit": "Cup",
        "twoName": "Whole-Grained Mustard",
        "threeAmount": "2",
        "threeUnit": "Lbs",
        "threeName": "Sirloin Steak",
        "fourAmount": "4",
        "fourUnit": " ",
        "fourName": "Onion Rolls",
        "fiveAmount": "1/2",
        "fiveUnit": "Tsp",
        "fiveName": "Kosher Salt",
        "sixAmount": "3",
        "sixUnit": "Tbsp",
        "sixName": "Butter"
      }],
      "instructions": [{
        "stepOne": 'Arrange a rack about 4 inches from the broiler and heat the broiler to high. Line a rimmed baking sheet with aluminum foil. Coat a wire rack with cooking spray and fit over the baking sheet.',
        "stepTwo": 'Pat the steak dry with a paper towel. Season both sides with the salt and pepper and place on the wire rack. Broil (the steak should be 1 to 2 inches from the broilers heating element) for 5 minutes',
        "stepThree": 'Let the steak rest for 10 minutes on the rack',
        "stepFour": 'Spread a thick layer of Dijon mayonnaise on the cut sides of the rolls. Divide the steak and arugula between the rolls and close them to form sandwiches. Serve warm or at room temperature.'
      }],
      "prepTime": '30 minutes'
    },
    {
      "dishName": 'Honey Chicken Kabobs',
      "imgUrl": 'https://images.unsplash.com/photo-1534797258760-1bd2cc95a5bd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      "starRating": 4,
      "briefDescription": "Honey chicken kabobs with veggies. You can marinate overnight and make these kabobs for an outdoor barbecue as a tasty alternative to the usual barbecue fare! Fresh mushrooms and cherry tomatoes can also be used.",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Chicken",
        "twoAmount": "1/2",
        "twoUnit": "Cup",
        "twoName": "Bell Peppers",
        "threeAmount": "2",
        "threeUnit": "Garlic",
        "threeName": "Cloves",
        "fourAmount": "1",
        "fourUnit": "Tsp",
        "fourName": "Soy Sauce",
        "fiveAmount": "5",
        "fiveUnit": " ",
        "fiveName": "Green Onions",
        "sixAmount": "1",
        "sixUnit": "Tsp",
        "sixName": "Black Pepper",
        "sevenAmount": "4",
        "sevenUnit": "Tsp",
        "sevenName": "Honey"
      }],
      "instructions": [{
        "stepOne": 'In a large bowl, whisk together oil, honey, soy sauce, and pepper. Before adding chicken, reserve a small amount of marinade to brush onto kabobs while cooking. Place the chicken, garlic, onions and peppers in the bowl, and marinate in the refrigerator at least 2 hours',
        "stepTwo": 'Preheat the grill for high heat.',
        "stepThree": 'Drain marinade from the chicken and vegetables, and discard marinade. Thread chicken and vegetables alternately onto the skewers',
        "stepFour": 'Lightly oil the grill grate. Place the skewers on the grill. Cook for 12 to 15 minutes, until chicken juices run clear. Turn and brush with reserved marinade frequently.'
      }],
      "prepTime": '35 minutes'
    },
    {
      "dishName": 'Slow Cooker Creamy Chicken Taco Soup',
      "imgUrl": 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      "starRating": 4,
      "briefDescription": "Reminiscent of the very popular dish King Ranch Chicken in the form a soup. With all the same flavors and the convenience of throwing everything into a slow cooker, this will also quickly become a favorite.",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Chicken",
        "twoAmount": "1/2",
        "twoUnit": "Cup",
        "twoName": "Chicken Broth",
        "threeAmount": "2",
        "threeUnit": " ",
        "threeName": "Garlic Cloves",
        "fourAmount": "1/3",
        "fourUnit": "Cup",
        "fourName": "Cheese",
        "fiveAmount": "5",
        "fiveUnit": " ",
        "fiveName": "Green Onions",
        "sixAmount": "1",
        "sixUnit": "Tsp",
        "sixName": "Black Pepper",
        "sevenAmount": "4",
        "sevenUnit": "",
        "sevenName": "Green Chilies"
      }],
      "instructions": [{
        "stepOne": 'Spray a slow cooker with cooking spray. Add onions, bell pepper, and 1 teaspoon salt. Stir in chicken broth, diced tomatoes, condensed soup, and chiles.',
        "stepTwo": 'Combine oil, taco seasoning, 1 teaspoon salt, cumin, and black pepper in a bowl. Add chicken and toss to coat on all sides. Transfer to the slow cooker.',
        "stepThree": 'Cook on Low until chicken is no longer pink in the center and the juices run clear, 2 to 3 hours. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C). Remove from the slow cooker and shred.',
        "stepFour": 'Add cheese to the slow cooker and stir until melted. Return chicken to the slow cooker and cook until warmed through, 20 to 30 minutes more.'
      }],
      "prepTime": '35 minutes'
    },
    {
      "dishName": 'Pan Shrimp and Sausage Bake',
      "imgUrl": 'https://images.unsplash.com/photo-1584208632869-05fa2b2a5934?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      "starRating": 4,
      "briefDescription": "Easy shrimp and sausage bake, delicious, healthier, and gluten free, all on one big sheet pan in the oven!",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Shrimp",
        "twoAmount": "1/2",
        "twoUnit": "Lbs",
        "twoName": "Yukon Gold Potatoes",
        "threeAmount": "2",
        "threeUnit": " ",
        "threeName": "Corn Ears",
        "fourAmount": "3",
        "fourUnit": "Tsp",
        "fourName": "Creole Seasoning",
        "fiveAmount": "5",
        "fiveUnit": "Tsp",
        "fiveName": "Minced Garlic",
        "sixAmount": "1",
        "sixUnit": "Tsp",
        "sixName": "Black Pepper",
        "sevenAmount": "1",
        "sevenUnit": "Tsp",
        "sevenName": "Paprika",
        "eightAmount": "1",
        "eightUnit": "Lbs",
        "eightName": "Bell Peppers"
      }],
      "instructions": [{
        "stepOne": 'Place potatoes into a large pot and cover with salted water; bring to a boil. Reduce heat to medium-low and simmer until tender, 10 to 12 minutes. Add corn and boil for an additional 5 minutes. Drain. Cut corn into thirds.',
        "stepTwo": 'Meanwhile, combine 3 tablespoons olive oil, 3 tablespoons Creole seasoning, juice from 1 lemon, garlic, Italian seasoning, 1/2 teaspoon paprika, red pepper flakes, salt, and pepper in a small bowl. Mix well to combine and set seasoning mixture aside.',
        "stepThree": 'Combine boiled potatoes and corn, all the bell peppers, cherry tomatoes, onion, and sausage slices in a large bowl. Add seasoning mixture and mix evenly.',
        "stepFour": 'Meanwhile, combine shrimp, 1 tablespoon olive oil, 1/2 teaspoon paprika, and 1/2 teaspoon Creole seasoning in a bowl. Marinate for a few minutes. Add shrimp to the sheet pan with the potato mixture after 8 minutes of baking and mix to combine.Return sheet pan to the oven and cook until shrimp are opaque, 6 to 8 minutes. Remove lemon wedges and garnish with parsley and green onions.'
      }],
      "prepTime": '35 minutes'
    },
    {
      "dishName": 'Spaghetti Sauce with Ground Beef',
      "imgUrl": 'https://images.unsplash.com/photo-1572441713132-c542fc4fe282?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      "starRating": 2,
      "briefDescription": "This recipe has been handed down from my mother. It is a family favorite and will not be replaced! (Definite party pleaser!)",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Ground Beef",
        "twoAmount": "1/2",
        "twoUnit": "Cup",
        "twoName": "Onion",
        "threeAmount": "1",
        "threeUnit": "Can",
        "threeName": "Diced Tomatoes",
        "fourAmount": "1",
        "fourUnit": "Can",
        "fourName": "Tomato Sauce",
        "fiveAmount": "4",
        "fiveUnit": "Tsp",
        "fiveName": "Minced Garlic",
        "sixAmount": "1",
        "sixUnit": "Tsp",
        "sixName": "Dried Oregano",
        "sevenAmount": "1",
        "sevenUnit": "Tsp",
        "sevenName": "Dried Basil",
        "eightAmount": "1",
        "eightUnit": "Lbs",
        "eightName": "Bell Peppers"
      }],
      "instructions": [{
        "stepOne": 'Combine ground beef, onion, garlic, and green pepper in a large saucepan.',
        "stepTwo": 'Cook and stir until meat is brown and vegetables are tender. Drain grease.',
        "stepThree": 'Stir diced tomatoes, tomato sauce, and tomato paste into the pan. ',
        "stepFour": 'Season with oregano, basil, salt, and pepper. Simmer spaghetti sauce for 1 hour, stirring occasionally.'
      }],
      "prepTime": '33 minutes'
    },
    {
      "dishName": 'Good Old Fashioned Pancakes',
      "imgUrl": 'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      "starRating": 5,
      "briefDescription": "This is a great recipe that I found in my Grandma's recipe book. Judging from the weathered look of this recipe card, this was a family favorite.",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Flour",
        "twoAmount": "1/2",
        "twoUnit": "Tsp",
        "twoName": "Baking Powder",
        "threeAmount": "1",
        "threeUnit": "Cup",
        "threeName": "Sugar",
        "fourAmount": "1 1/4",
        "fourUnit": "Cup",
        "fourName": "Milk",
        "fiveAmount": "4",
        "fiveUnit": " ",
        "fiveName": "Eggs",
        "sixAmount": "1",
        "sixUnit": "Tbsp",
        "sixName": "Butter",
        "sevenAmount": "1",
        "sevenUnit": "Tsp",
        "sevenName": "Salt"
      }],
      "instructions": [{
        "stepOne": 'In a large bowl, sift together the flour, baking powder, salt and sugar.',
        "stepTwo": 'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
        "stepThree": 'Heat a lightly oiled griddle or frying pan over medium high heat. ',
        "stepFour": 'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'
      }],
      "prepTime": '25 minutes'
    },
    {
      "dishName": 'Brownies',
      "imgUrl": 'https://images.unsplash.com/photo-1515037893149-de7f840978e2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      "starRating": 4,
      "briefDescription": "These brownies are the bomb! I've found the perfect combination of ingredients to make the fudgiest brownies yet... Enjoy!",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Flour",
        "twoAmount": "1/2",
        "twoUnit": "Tsp",
        "twoName": "Baking Powder",
        "threeAmount": "1",
        "threeUnit": "Cup",
        "threeName": "Cocoa Powder",
        "fourAmount": "1 1/4",
        "fourUnit": "Cup",
        "fourName": "Milk",
        "fiveAmount": "4",
        "fiveUnit": " ",
        "fiveName": "Eggs",
        "sixAmount": "1",
        "sixUnit": "Tbsp",
        "sixName": "Butter",
        "sevenAmount": "1",
        "sevenUnit": "Tsp",
        "sevenName": "Salt",
        "eightAmount": "1",
        "eightUnit": "Cup",
        "eightName": "Chocolate Chips"
      }],
      "instructions": [{
        "stepOne": 'Preheat oven to 350 degrees F (175 degrees C). Lightly grease a 9x13 baking dish.',
        "stepTwo": 'Combine the melted butter, sugar, and vanilla in a large bowl. Beat in the eggs, one at a time, mixing well after each, until thoroughly blended.',
        "stepThree": 'Sift the flour, cocoa powder, and salt in a bowl. Gradually stir flour mixture into the egg mixture until blended. Stir in the chocolate morsels. Spread the batter evenly into the prepared baking dish',
        "stepFour": 'Bake in preheated oven until an inserted toothpick comes out clean, 35 to 40 minutes. Remove, and cool pan on wire rack before cutting.'
      }],
      "prepTime": '20 minutes'
    },
    {
      "dishName": 'Chocolate Chip Cookies',
      "imgUrl": 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      "starRating": 4,
      "briefDescription": "I received this recipe through a cookie exchange years ago, and it has become a favorite of family and friends.",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Flour",
        "twoAmount": "1/2",
        "twoUnit": "Tsp",
        "twoName": "Baking Powder",
        "threeAmount": "1",
        "threeUnit": "Cup",
        "threeName": "Brown Sugar",
        "fourAmount": "1 1/4",
        "fourUnit": "Cup",
        "fourName": "Milk",
        "fiveAmount": "2",
        "fiveUnit": " ",
        "fiveName": "Eggs",
        "sixAmount": "1",
        "sixUnit": "Tbsp",
        "sixName": "Butter",
        "sevenAmount": "1",
        "sevenUnit": "Tsp",
        "sevenName": "Salt",
        "eightAmount": "1",
        "eightUnit": "Cup",
        "eightName": "Chocolate Chips"
      }],
      "instructions": [{
        "stepOne": 'In a saucepan over medium heat, cook the sugar, butter and water, stirring occasionally until melted. Remove from heat, stir in the chocolate chips until melted and set aside to cool for 10 minutes.',
        "stepTwo": 'Pour the chocolate mixture into a large bowl, and beat in the eggs, one at a time. Combine the flour, baking soda and salt, stir into the chocolate mixture. Cover and refrigerate dough for at least 1 hour.',
        "stepThree": 'Preheat oven to 350 degrees F (175 degrees C). Grease cookie sheets. Roll cookie dough into walnut sized balls and place 2 inches apart onto the prepared cookie sheets.',
        "stepFour": 'Bake for 8 to 10 minutes in the preheated oven, be careful not to overbake. When cookies come out of the oven, Press one mint wafer into the top of each cookie and let sit for 1 minute.'
      }],
      "prepTime": '20 minutes'
    },
    {
      "dishName": 'Grilled Baby Back Ribs',
      "imgUrl": 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      "starRating": 4,
      "briefDescription": "Man, when your guests bite into these at the Memorial Day cookout, they'll savor meat so tender and juicy that it slides right off the bone and gets you the respect you deserve! ",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Baby Back Pork Ribs",
        "twoAmount": "1",
        "twoUnit": "Tsp",
        "twoName": "Red Chile Powder",
        "threeAmount": "1",
        "threeUnit": "Cup",
        "threeName": "Water",
        "fourAmount": "1/4",
        "fourUnit": "Cup",
        "fourName": "Tomato Paste",
        "fiveAmount": "1/2",
        "fiveUnit": "Cup",
        "fiveName": "Vinegar",
        "sixAmount": "1/2",
        "sixUnit": "Cup",
        "sixName": "Brown Sugar",
        "sevenAmount": "1",
        "sevenUnit": "Tsp",
        "sevenName": "Worcestershire Sauce",
        "eightAmount": "1/4",
        "eightUnit": "Tsp",
        "eightName": "Black Pepper"
      }],
      "instructions": [{
        "stepOne": 'Cut each full rack of ribs in half, so that you have 4 half racks. Sprinkle salt and pepper (more pepper than salt), and 1 tablespoon chile pepper over meat. Wrap each half rack in aluminum foil. Bake for 2 1/2 hours.',
        "stepTwo": 'Meanwhile, heat oil in a medium saucepan over medium heat. Cook and stir the onions in oil for 5 minutes. Stir in water, tomato paste, vinegar, brown sugar, honey, and Worcestershire sauce. Season with 2 teaspoons salt, 1/4 teaspoon black pepper, liquid smoke, whiskey, garlic powder, paprika, onion powder, dark molasses, and 1/2 tablespoon ground chile pepper.',
        "stepThree": ' Bring mixture to a boil, then reduce heat. Simmer for 1 1/4 hours, uncovered, or until sauce thickens. Remove from heat, and set sauce aside.',
        "stepFour": 'Remove the ribs from the oven, and let stand 10 minutes. Remove the racks from the foil, and place on the grill. Grill the ribs for 3 to 4 minutes on each side. Brush sauce on the ribs while they are grilling'
      }],
      "prepTime": '45 minutes'
    },
    {
      "dishName": 'Italian Chicken Marinade',
      "imgUrl": 'https://images.unsplash.com/photo-1496074620649-6b1b02e5c1c8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      "starRating": 5,
      "briefDescription": "This is a simple but delicious way of marinating your chicken.",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Boneless Chicken Breasts",
        "twoAmount": "1/2",
        "twoUnit": "Cup",
        "twoName": "Red Chile Powder",
        "threeAmount": "1",
        "threeUnit": "Tsp",
        "threeName": "Garlic Powder",
        "fourAmount": "1/4",
        "fourUnit": "Cup",
        "fourName": "Italian-Style Dressing",
        "fiveAmount": "1",
        "fiveUnit": "Tsp",
        "fiveName": "Paprika",
        "sixAmount": "1",
        "sixUnit": "Tsp",
        "sixName": "Salt",
        "sevenAmount": "1",
        "sevenUnit": "Tsp",
        "sevenName": "Spicy Marinade",
        "eightAmount": "1/4",
        "eightUnit": "Tsp",
        "eightName": "Black Pepper"
      }],
      "instructions": [{
        "stepOne": 'In a shallow baking dish, mix the salad dressing, garlic powder, and salt. Place the chicken in the bowl, and turn to coat.',
        "stepTwo": 'Marinate in the refrigerator at least 4 hours.',
        "stepThree": 'Preheat the grill for high heat.',
        "stepFour": 'Lightly oil grate. Discard marinade, and grill chicken 8 minutes on each side, or until juices run clear.'
      }],
      "prepTime": '28 minutes'
    },
    {
      "dishName": 'Grilled Marinated Shrimp',
      "imgUrl": 'https://images.unsplash.com/photo-1548179015-b23bec2b1a2a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      "starRating": 3,
      "briefDescription": "This makes the best shrimp! Remove from skewers and serve on a bed of pasta with sauce for a great meal.",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Shrimp",
        "twoAmount": "1/4",
        "twoUnit": "Cup",
        "twoName": "Parsley",
        "threeAmount": "1",
        "threeUnit": "Tsp",
        "threeName": "Garlic Powder",
        "fourAmount": "1/4",
        "fourUnit": "Cup",
        "fourName": "Frank's Hot Sauce",
        "fiveAmount": "1",
        "fiveUnit": "Garlic",
        "fiveName": "Clove",
        "sixAmount": "1",
        "sixUnit": "Tsp",
        "sixName": "Dried Oregano",
        "sevenAmount": "1",
        "sevenUnit": "Tsp",
        "sevenName": "Salt",
        "eightAmount": "1/4",
        "eightUnit": "Tsp",
        "eightName": "Black Pepper"
      }],
      "instructions": [{
        "stepOne": 'In a mixing bowl, mix together olive oil, parsley, lemon juice, hot sauce, garlic, tomato paste, oregano, salt, and black pepper. ',
        "stepTwo": 'Reserve a small amount for basting later. Pour remaining marinade into a large resealable plastic bag with shrimp. Seal, and marinate in the refrigerator for 2 hours.',
        "stepThree": 'Preheat grill for medium-low heat. Thread shrimp onto skewers, piercing once near the tail and once near the head. Discard marinade.',
        "stepFour": 'Lightly oil grill grate. Cook shrimp for 5 minutes per side, or until opaque, basting frequently with reserved marinade.'
      }],
      "prepTime": '35 minutes'
    },
    {
      "dishName": "Krabby Patty",
      "imgUrl": 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQiDmTgtt-oNkYeXv5ER4Iz9ky32e6cKDyNWQ&usqp=CAU',
      "starRating": 5,
      "briefDescription": "Straight from under the sea!",
      "ingredients": [{
        "oneAmount": "1/3",
        "oneUnit": "Lbs",
        "oneName": "Ground Beef",
        "twoAmount": "2",
        "twoUnit": "Tsp",
        "twoName": "Old Bay Seasoning",
        "threeAmount": "1",
        "threeUnit": "Tsp",
        "threeName": "Black Pepper",
        "fourAmount": "1",
        "fourUnit": "Tsp",
        "fourName": "Salt",
        "fiveAmount": "1/4",
        "fiveUnit": "Lbs",
        "fiveName": "Cheddar Cheese",
        "sixAmount": "4",
        "sixUnit": " ",
        "sixName": "Hamburger Buns",
        "sevenAmount": "1/4",
        "sevenUnit": "Lbs",
        "sevenName": "Lettuce"
      }],
      "instructions": [{
        "stepOne": ' Heat a grill pan or sauté pan over medium heat. As it heats, combine ground beef, Old Bay, pepper and salt. Form into four equally sized patties, about 1/3 lb apiece.',
        "stepTwo": 'Set on a platter next to the stove top. Coat the warmed grill pan with cooking spray and place patties on the pan, cooking each side about 4-5 minutes, or until cooked through to your desired doneness.',
        "stepThree": 'Use a large star-shaped cookie cutter to cut each cheese slice into a star shape. Place the star-shaped cheese on each burger patty, in the last 30 seconds or so of cooking, so it melts a little. Set burger patties aside.',
        "stepFour": 'Spread Poseidon Powder Aioli on the bottom of each bun. Top with a burger patty, ketchup, mustard, pickles, onion slices, tomato and lettuce. Place the top bun on each burger. Serve.'
      }],
      "prepTime": '25 minutes'
    },
    {
      "dishName": "Spinach and Feta Turkey Burgers",
      "imgUrl": 'https://images.unsplash.com/photo-1559466273-d95e72debaf8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      "starRating": 5,
      "briefDescription": "These are a big hit in the summertime when everyone is tired of the same old hamburgers and hot dogs. Serve with or without buns and your favorite condiments. I like to serve these with lettuce, tomato, and Tzatziki sauce.",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Ground Turkey",
        "twoAmount": "1/4",
        "twoUnit": "Lbs",
        "twoName": "Green Onion",
        "threeAmount": "2",
        "threeUnit": " ",
        "threeName": "Eggs",
        "fourAmount": "4",
        "fourUnit": "Oz",
        "fourName": "Feta Cheese",
        "fiveAmount": "10",
        "fiveUnit": "Oz",
        "fiveName": "Spinach",
        "sixAmount": "2",
        "sixUnit": " ",
        "sixName": "Tomatoes",
        "sevenAmount": "4",
        "sevenUnit": "",
        "sevenName": "Hamburger Buns"
      }],
      "instructions": [{
        "stepOne": 'Preheat an outdoor grill for medium-high heat and lightly oil grate.',
        "stepTwo": 'While the grill is preheating, mix together eggs, garlic, feta cheese, spinach, and turkey in a large bowl',
        "stepThree": 'Form into 4 patties.',
        "stepFour": 'Cook on preheated grill until no longer pink in the center, 15 to 20 minutes.'
      }],
      "prepTime": '35 minutes'
    }, {
      "dishName": "Grilled Pork Chops with Basil-Garlic Rub",
      "imgUrl": "https://lh3.googleusercontent.com/KQlVT3lrsGGQTcx9CXi_tHFLl0na9OSo_oGqRzF-iObzfR5IZvgHU051g0iwDPrWG23ZQKCSEggibdswiEOM=s640-c-rw-v1-e365",
      "starRating": 4,
      "briefDescription": "Top the chop with shavings of Parmesan cheese (shave from a wedge of cheese with a vegetable peeler) and toasted pine nuts, if desired. Serve with slices of ripe tomatoes and mozzarella on a bed of arugula drizzled with balsamic vinegar and olive oil.",
      "ingredients": [{
        "oneAmount": "4",
        "oneUnit": " ",
        "oneName": "Bone-in Ribyeye Pork Chops",
        "twoAmount": "2",
        "twoUnit": "cloves",
        "twoName": "Garlic",
        "threeAmount": "1",
        "threeUnit": "Cup",
        "threeName": "Basil",
        "fourAmount": "2",
        "fourUnit": "Tbsp",
        "fourName": "Lemon Juice",
        "fiveAmount": "2",
        "fiveUnit": "Tbsp",
        "fiveName": "Extra Virgin Olive Oil",
        "sixAmount": "1/2",
        "sixUnit": "Tsp",
        "sixName": "Black Pepper"
      }],
      "instructions": [{
        "stepOne": "With machine running, drop garlic through feed tube of food processor to mince. Stop, add fresh basil, and process until chopped.",
        "stepTwo": "Add lemon juice, oil, salt, and pepper and process to make thin wet rub. Spread both sides of pork chops with basil mixture. Let stand 15 to 30 minutes.",
        "stepThree": "Prepare a medium-hot fire in grill. Brush the grate clean and oil the grate.",
        "stepFour": "Grill chops, over direct heat, turning once, to medium rare doneness, 5 to 6 minutes per side, or until the internal temperature reaches 145 degrees Fahrenheit, followed by a 3-minute rest time."
      }],
      "prepTime": "40 minutes"
    },
    {
      "dishName": "Korean Pork Chops",
      "imgUrl": "https://lh3.googleusercontent.com/6gidAEevFeE6xiMpD7YWKMnFlKwtUQSUZyiWg0d390kpCZ88ttg1Wa1VXbWe5dIz10_jT1392PBFtpanls76=s640-c-rw-v1-e365",
      "starRating": 5,
      "briefDescription": "Quick, delicious, and easy Korean style Pork Chops.",
      "ingredients": [{
        "oneAmount": "4",
        "oneUnit": " ",
        "oneName": "New York Top Loin Pork Chops",
        "twoAmount": "1/2",
        "twoUnit": "tbsp",
        "twoName": "Soy Sauce",
        "threeAmount": "4",
        "threeUnit": "Tbsp",
        "threeName": "Honey",
        "fourAmount": "2",
        "fourUnit": "Tsp",
        "fourName": "Sesame Oil",
        "fiveAmount": "4",
        "fiveUnit": "Tsp",
        "fiveName": "Ginger Root (grated)",
        "sixAmount": "2",
        "sixUnit": "Tbsp",
        "sixName": "Sweet Chili Sauce"
      }],
      "instructions": [{
        "stepOne": "In a medium size bowl whisk together soy sauce, honey, garlic, ginger, sesame oil and sweet chili sauce. It’ll make just over 1 cup of marinade.Reserve half the marinade, set aside.",
        "stepTwo": "Pour the other half of the marinade over pork chops and marinate for at least 10 minutes. Heat olive oil in a large skillet over medium-high heat; add pork chops to skillet, discard remaining marinade.",
        "stepThree": "Cook for 5 minutes or until chops have browned on one side.",
        "stepFour": "Flip the pork chops and add the reserved marinade to the pan; cook for 5 more minutes or until the pork reaches an internal temperature between 145 degrees F. (medium rare) and 160 degrees F. (medium). Let rest for 3 minutes before serving."
      }],
      "prepTime": "20 minutes"
    }, {
      "dishName": "Garlic Butter Pork Chops",
      "imgUrl": "https://lh3.googleusercontent.com/Cs8YDW1RViJWxwOMXg_8GsOuuRT64bkHBNrYXyajlH5YDxrSJTtP_5VlkiC27q5yvpqw9nz7bHGhWgvIAwmw=s640-c-rw-v1-e365",
      "starRating": 4,
      "briefDescription": "Easy and delicious pork dish.",
      "ingredients": [{
        "oneAmount": "2",
        "oneUnit": "Lbs",
        "oneName": "Boneless Pork Chops",
        "twoAmount": "1/2",
        "twoUnit": "Tbsp",
        "twoName": "Salt",
        "threeAmount": "1/2",
        "threeUnit": "Tbsp",
        "threeName": "Black Pepper",
        "fourAmount": "2",
        "fourUnit": "Tbsp",
        "fourName": "Olive Oil",
        "fiveAmount": "4",
        "fiveUnit": "Tbsp",
        "fiveName": "Butter",
        "sixAmount": "1",
        "sixUnit": "Tsp",
        "sixName": "Thyme",
        "sevenAmount": "5",
        "sevenUnit": "cloves",
        "sevenName": "Garlic"
      }],
      "instructions": [{
        "stepOne": "Season both sides of the pork chops with salt and ground black pepper.",
        "stepTwo": "Heat a skillet on medium-high heat. Add the oil,butter, and thyme. Pan sear and cook the pork chops for about 3 minutes on each side, or until the surface turns light golden brown.",
        "stepThree": "Add the garlic to the skillet. Continue to flip the pork chops around and saute the garlic until light brown. Season with more salt if desired.",
        "stepFour": "Remove the pork chops from heat and serve immediately."
      }],
      "prepTime": "20 minutes"
    }, {
      "dishName": "Parmesan Baked Pork Chops",
      "imgUrl": "https://lh3.googleusercontent.com/SrZOd45QwotI5baTKwupRgxA8hanLLu1JKz638EyOpIfPsYHpUESJJPAWWEgrAF-B4je0U-DaQ3mckrTN7YlFjg=s640-c-rw-v1-e365",
      "briefDescription": "Who doesn't like parmesean and pork chops?",
      "starRating": 5,
      "ingredients": [{
        "oneAmount": "4",
        "oneUnit": " ",
        "oneName": "Boneless Pork Chops",
        "twoAmount": "1",
        "twoUnit": "Tbsp",
        "twoName": "Olive Oil",
        "threeAmount": "1",
        "threeUnit": "Cup",
        "threeName": "Parmesean Cheese",
        "fourAmount": "1",
        "fourUnit": "Cup",
        "fourName": "Italian Bread Crumbs",
        "fiveAmount": "1",
        "fiveUnit": "Tsp",
        "fiveName": "Black Pepper",
        "sixAmount": "1",
        "sixUnit": "Tsp",
        "sixName": "Garlic Powder"
      }],
      "instructions": [{
        "stepOne": "On a plate combine the last 4 ingredients.",
        "stepTwo": "Rub the pork chops with olive oil and then dip (coat) each one in the cheese mixture. Press the mixture over the pork chops to make sure they are well covered in it.",
        "stepThree": "Line a pan with tin foil and spray with cooking spray.",
        "stepFour": "Place the pork chops on the pan and bake at 350 degrees for 40-45 minutes."
      }],
      "prepTime": "45 minutes"
    }, {
      "dishName": "Instant Pot Asian-Inspired Pork Shoulder",
      "imgUrl": "https://lh3.googleusercontent.com/5MhUzNl3YyhIK3--SIs6nq-llEW8DacZwHbsL8kuiS4XbDXaSn1ezqaC1PE7ZqFv9SO7-PIg-ONyxQPf03mj3g=s640-c-rw-v1-e365",
      "briefDescription": "This Instant Pot recipe for tender pork butt comes from Daniel Shumski, author of the cookbook 'How to Instant Pot: Mastering All the Functions of the One Pot That Will Change the Way You Cook.' In this easy pork recipe, you'll take advantage of store-bought sauce and, of course, the electric pressure cooker to get your main course prepared in 10 minutes flat (hello, weeknight meal!).",
      "starRating": 4,
      "ingredients": [{
        "oneAmount": "4",
        "oneUnit": " ",
        "oneName": "New York Top Loin Pork Chops",
        "twoAmount": "1/2",
        "twoUnit": "tbsp",
        "twoName": "Soy Sauce",
        "threeAmount": "4",
        "threeUnit": "Tbsp",
        "threeName": "Honey",
        "fourAmount": "2",
        "fourUnit": "Tsp",
        "fourName": "Sesame Oil",
        "fiveAmount": "4",
        "fiveUnit": "Tsp",
        "fiveName": "Ginger Root (grated)",
        "sixAmount": "2",
        "sixUnit": "Tbsp",
        "sixName": "Sweet Chili Sauce"
      }],
      "instructions": [{
        "stepOne": "In a medium size bowl whisk together soy sauce, honey, garlic, ginger, sesame oil and sweet chili sauce. It’ll make just over 1 cup of marinade.Reserve half the marinade, set aside.",
        "stepTwo": "Pour the other half of the marinade over pork chops and marinate for at least 10 minutes. Heat olive oil in a large skillet over medium-high heat; add pork chops to skillet, discard remaining marinade.",
        "stepThree": "Cook for 5 minutes or until chops have browned on one side.",
        "stepFour": "Flip the pork chops and add the reserved marinade to the pan; cook for 5 more minutes or until the pork reaches an internal temperature between 145 degrees F. (medium rare) and 160 degrees F. (medium). Let rest for 3 minutes before serving."
      }],
      "prepTime": "20 minutes"
    }, {
      "dishName": "Boneless Pork Loin Roast with Herbed Pepper Rub",
      "imgUrl": "https://lh3.googleusercontent.com/hEyxINaskvAB5xnHbayRjZR7CCc3jbAa5eaY7hcXEmYkMhkV2XZHaO1Wc4eNVBEsTe9HUAREnJ9g8YqXY1bofQ=s640-c-rw-v1-e365",
      "briefDescription": "Family favorite",
      "starRating": "4",
      "ingredients": [{
        "oneAmount": "3",
        "oneUnit": "lbs",
        "oneName": "Pork Loin Roast, boneless",
        "twoAmount": "2",
        "twoUnit": "tbsp",
        "twoName": "Black Pepper",
        "threeAmount": "2",
        "threeUnit": "Tbsp",
        "threeName": "Parmesan Cheese",
        "fourAmount": "2",
        "fourUnit": "Tsp",
        "fourName": "Dried Basil",
        "fiveAmount": "2",
        "fiveUnit": "Tsp",
        "fiveName": "Rosemary",
        "sixAmount": "2",
        "sixUnit": "Tsp",
        "sixName": "Thyme",
        "sevenAmount": "1/4",
        "sevenUnit": "Tsp",
        "sevenName": "Garlic Powder",
        "eightAmount": "1/4",
        "eightUnit": "Tsp",
        "eightName": "Salt"
      }],
      "instructions": [{
        "stepOne": "Pat pork dry with paper towel. In small bowl, combine all rub ingredients well and apply to all surfaces of the pork roast.",
        "stepTwo": "Place roast in a shallow pan and roast in a 350 degrees F oven for 1 hour (20 minutes per pound), until internal temperature on a meat thermometer reads 145 degrees F.",
        "stepThree": "Remove roast from oven.",
        "stepFour": "Let rest about 10 minutes before slicing to serve."
      }],
      "prepTime": "65 minutes"
    }, {
      "dishName": "Easy Chicken Enchiladas",
      "imgUrl": "https://d1doqjmisr497k.cloudfront.net/-/media/mccormick-us/recipes/gourmet/s/800/shredded-chicken-enchiladas.jpg?vd=20180710T024404Z&hash=C3332779992D30906A4761A33A1B94D24C634C1D",
      "briefDescription": "Restaurant-quality enchiladas have never been easier! These mouthwatering chicken- and cheese-filled corn tortillas are doused in spicy red sauce and baked in the oven. With just 5 ingredients and 10 minutes of hands-on time, you'll have a delicious dinner in less time than it takes to pick up takeout.",
      "starRating": 5,
      "ingredients": [{
        "oneAmount": "2",
        "oneUnit": "Cans",
        "oneName": "Red Enchilada Sauce",
        "twoAmount": "12",
        "twoUnit": "Oz",
        "twoName": "Shredded Rotisserie Chicken",
        "threeAmount": "2",
        "threeUnit": "Cups",
        "threeName": "Mexican Cheese",
        "fourAmount": "12",
        "fourUnit": " ",
        "fourName": "Soft Corn Tortillas",
        "fiveAmount": "2",
        "fiveUnit": "Tsp",
        "fiveName": "Cilantro",
      }],
      "instructions": [{
        "stepOne": "Preheat the oven to 350°F. Spoon about 1/2 cup of enchilada sauce into the bottom of a 9x13-inch casserole dish. Set aside.",
        "stepTwo": "Place shredded chicken, shredded cheese, and 3/4 cup of the enchilada sauce in a mixing bowl. Mix with a rubber spatula to combine. Place a few tortillas on a dinner plate and warm in the microwave for 20-30 seconds, until pliable. Repeat with remaining tortillas.",
        "stepThree": "Spoon about 1/4 cup of the chicken and cheese mixture into the center of a tortilla. Gently roll the enchilada and place it seam-side down into the sauced casserole dish. Repeat with the remaining tortillas. Pour the remaining enchilada sauce evenly over the rolled tortillas. Sprinkle the shredded cheese over the top. Cover the dish with a sheet of aluminum foil.",
        "stepFour": "Bake the enchiladas for 20 minutes on the middle rack of oven. Remove the foil and continue baking 7-10 minutes longer, until the edges are bubbling and the cheese on top is slightly golden brown. Allow the dish to rest for 10 minutes. Sprinkle with cilantro, and serve."
      }],
      "prepTime": "50 minutes"
    }, {
      "dishName": "Honey-Mustard Chicken Breasts",
      "imgUrl": "https://diethood.com/wp-content/uploads/2019/04/Honey-Mustard-Chicken-5.jpg",
      "briefDescription": "This easy crowd-pleaser is made with just a few simple seasonings that you may already have on hand.",
      "starRating": "4",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "lbs",
        "oneName": "Chicken Breast",
        "twoAmount": "1/4",
        "twoUnit": "Cup",
        "twoName": "Whole Grain Mustard",
        "threeAmount": "1/4",
        "threeUnit": "Cup",
        "threeName": "Honey",
        "fourAmount": "1/2",
        "fourUnit": "Tsp",
        "fourName": "Garlic Powder",
        "fiveAmount": "2",
        "fiveUnit": "Tsp",
        "fiveName": "Olive Oil"
      }],
      "instructions": [{
        "stepOne": "Preheat the oven to 425°F. Line a large sheet pan with parchment paper.",
        "stepTwo": "Combine the garlic powder, mustard, honey, and olive oil in a medium mixing bowl. Add the chicken breasts one by one, and turn to coat in the mixture. Spread the chicken breasts out on the lined sheet pan.",
        "stepThree": "Insert the sheet pan into the oven, and bake for 15 minutes. Remove the sheet pan from the oven when the thickest part of the chicken has reached an internal temperature of 165°F.",
        "stepFour": "Allow the chicken to rest for approximately 5 minutes before serving."
      }],
      "prepTime": "25 minutes"
    }, {
      "dishName": "Melt In Your Mouth (MIYM) Chicken Breasts",
      "imgUrl": "https://lh3.googleusercontent.com/lrkA9oMH7bSZMAIhFREgZKw0G_fKvBu_-UmaoIM77diZ2ngZnFGaErTi00WAP5saAZquHjbYX0UtkzvQu9D4mw0=s640-c-rw-v1-e365",
      "briefDescription": "The dish name explains it all.",
      "starRating": "4",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Cup",
        "oneName": "Sour Cream",
        "twoAmount": "2",
        "twoUnit": "Tsp",
        "twoName": "Garlic Powder",
        "threeAmount": "1",
        "threeUnit": "Tsp",
        "threeName": "Salt",
        "fourAmount": "1/2",
        "fourUnit": "Tsp",
        "fourName": "Black Pepper",
        "fiveAmount": "1 1/2",
        "fiveUnit": "Cups",
        "fiveName": "Parmesean Cheese (grated)",
        "sixAmount": "3",
        "sixUnit": "Lbs",
        "sixName": "Boneless Chicken Breasts"
      }],
      "instructions": [{
        "stepOne": "Preheat oven to 375°F. Lightly coat a 9×13 baking dish with nonstick spray and set aside. In a medium bowl, mix together the sour cream, garlic powder, seasoned salt, pepper, and 1 cup of Parmesan cheese.",
        "stepTwo": "Place the chicken breasts evenly into the pan. Spread the sour cream mixture on top of the chicken. Sprinkle with the remaining Parmesan cheese.",
        "stepThree": "Bake for 25-30 minutes, or until the chicken is cooked through. Turn the oven to broil and place the pan under the broiler for 2-3 minutes until lightly browned on top.",
        "stepFour": "Serve immediately."
      }],
      "prepTime": "30 minutes"
    }, {
      "dishName": "Baked Buffalo Chicken Tenders",
      "imgUrl": "https://lh3.googleusercontent.com/eKVIn3GeMEem8evIhslRmt_s9-knj-VKAZ_x21qhEv3rrfOTgIpt606kTkfD8X-c4MAig31U1-bn3ySHLrH7nw=s640-c-rw-v1-e365",
      "briefDescription": "These juicy Buffalo chicken tenders are a spicy baked dish that people of any age can enjoy! With ranch dressing, these super easy baked chicken dippers make a great main dish for a weeknight dinner or tailgating party for finger foods with a healthy slant.",
      "starRating": 4,
      "ingredients": [{
        "oneAmount": "2/3",
        "oneUnit": "Cups",
        "oneName": "All-purpose Flour",
        "twoAmount": "1/2",
        "twoUnit": "tsp",
        "twoName": "Cayenne Pepper",
        "threeAmount": "1/2",
        "threeUnit": "Tsp",
        "threeName": "Paprika",
        "fourAmount": "1/2",
        "fourUnit": "Tsp",
        "fourName": "Garlic Powder",
        "fiveAmount": "1/2",
        "fiveUnit": "Tsp",
        "fiveName": "Salt",
        "sixAmount": "3",
        "sixUnit": " Lbs",
        "sixName": "Boneless Skinless Chicken Breasts",
        "sevenAmount": "1/2",
        "sevenUnit": "Cup",
        "sevenName": "Butter",
        "eightUnit": "1/2",
        "eightAmount": "Cup",
        "eightName": "Hot Sauce"
      }],
      "instructions": [{
        "stepOne": "Line baking dish or cookie sheet with aluminum foil, and spray it lightly with cooking spray. Coat chicken tenders thoroughly in a mixture of the flour (or panko breadcrumbs), cayenne, paprika, garlic powder, and salt. Shake off excess flour or panko breadcrumbs.",
        "stepTwo": "Place chicken strips onto the prepared baking sheet. Refrigerate for at least one hour. Preheat oven to 400 degrees Fahrenheit (200 degrees Celsius).",
        "stepThree": "Whisk together the melted butter and hot sauce in a small bowl. Dip the chicken tenders into the butter mixture and place them back on the baking sheet. Bake chicken tenders until they are no longer pink in the center, and golden brown on the outside. It should take about 45 minutes. Turn the chicken tenders over halfway during cooking so they cook evenly.",
        "stepFour": "Serve immediately."
      }],
      "prepTime": "95 minutes"
    }, {
      "dishName": "Classic Chicken Salad",
      "imgUrl": "https://lh3.googleusercontent.com/cTFR7Eoi8lWhXi4y01h3qomuiy2wPLiCanB_smcDUyH2tfVC5VlvjcSngY7Ph1Tt8hU-YwONwlw0BSDrmEvA5Q=s640-c-rw-v1-e365",
      "briefDescription": "Versatile and easy dish.",
      "starRating": 3,
      "ingredients": [{
        "oneAmount": "4",
        "oneUnit": "Cups",
        "oneName": "Cooked Chicken Breasts",
        "twoAmount": "1/4",
        "twoUnit": "tsp",
        "twoName": "Salt",
        "threeAmount": "1/4",
        "threeUnit": "Tsp",
        "threeName": "Black Pepper",
        "fourAmount": "1",
        "fourUnit": "Cup",
        "fourName": "Mayonnaise",
        "fiveAmount": "2",
        "fiveUnit": "Tbsp",
        "fiveName": "Lemon Juice",
        "sixAmount": "1/2",
        "sixUnit": "Cup",
        "sixName": "Diced Celery",
        "sevenAmount": "1/4",
        "sevenUnit": "Cup",
        "sevenName": "Sliced Almonds"
      }],
      "instructions": [{
        "stepOne": "Mix all the ingredients well in a bowl.",
        "stepTwo": "Refigerate for at least 1 hour.",
        "stepThree": "Serve with bread, wrap, or any side dish.",
        "stepFour": "Enjoy!"
      }],
      "prepTime": "1 hour"
    }, {
      "dishName": "Keto Crack Chicken in the Crock Pot",
      "imgUrl": "https://lh3.googleusercontent.com/c8g8LHCPFWhGFYt2flU8U9enxTF58YIUuLkE5zG69Nfe_ZeuCDVHqJvZTYg_3SITV_FMpr67Wh9e951XnBauBw=s640-c-rw-v1-e365",
      "briefDescription": "Crock pot meal that is easy and delicious!",
      "starRating": 4,
      "ingredients": [{
        "oneAmount": "1/2",
        "oneUnit": "Cup",
        "oneName": "Chicken Broth",
        "twoAmount": "1",
        "twoUnit": " ",
        "twoName": "Ranch Seasoning Packet",
        "threeAmount": "2",
        "threeUnit": "Lbs",
        "threeName": "Chicken Breasts",
        "fourAmount": "8",
        "fourUnit": "Oz",
        "fourName": "Cream Cheese",
        "fiveAmount": "8",
        "fiveUnit": "Slices",
        "fiveName": "Crumbled Bacon",
        "sixAmount": "1/2",
        "sixUnit": "Cup",
        "sixName": "Shredded Cheddar Cheese"
      }],
      "instructions": [{
        "stepOne": "Add chicken broth to the slow cooker and stir in Hidden Valley Ranch seasoning packet. Then add defrosted chicken breasts.",
        "stepTwo": "Cover and cook for 4 hours on high or 8 hours on low. After the cook time has ended, shred the chicken with two forks.",
        "stepThree": "Add chunks of cut up Cream Cheese, bacon and shredded cheddar. Stir ingredients.",
        "stepFour": "Cover the crock pot again, and cook for an additional 5-10 minutes, until the cream cheese has melted."
      }],
      "prepTime": "4 hours"
    }, {
      "dishName": "Instant Pot Turkey Breast",
      "imgUrl": "https://lh3.googleusercontent.com/UgbOf3hhFEIngaDLyQ6jqORbvfsB4DgmRRgrjypruLRgUmi2DFr87sut_b5pQ5fuv3UstGUquto8D_BTyXG8=s640-c-rw-v1-e365",
      "briefDescription": "Tender, flavorful turkey breast, made in under 45 minutes cook time from start to finish!.",
      "starRating": 3,
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Bone-in, skin-on Turkey Breast Halves",
        "twoAmount": "2",
        "twoUnit": "Tsp",
        "twoName": "Salt",
        "threeAmount": "1/2",
        "threeUnit": "Tsp",
        "threeName": "Black Pepper",
        "fourAmount": "2",
        "fourUnit": "Tsp",
        "fourName": "Thyme",
        "fiveAmount": "1",
        "fiveUnit": "Tsp",
        "fiveName": "Sage",
        "sixAmount": "1",
        "sixUnit": "Tsp",
        "sixName": "Garlic Powder",
        "sevenAmount": "2",
        "sevenUnit": "Cups",
        "sevenName": "Chicken Broth"
      }],
      "instructions": [{
        "stepOne": "Pat the turkey breasts dry with paper towels. Season liberally on both sides with the salt and pepper, then sprinkle with the thyme, sage, and garlic powder.",
        "stepTwo": "Insert the trivet/steamer rack into the bowl of the Instant Pot, and pour in the chicken broth. Lay the turkey breasts inside the trivet.",
        "stepThree": "Secure the lid on the Instant Pot. Set the timer to 35 minutes on the “Pressure Cook” setting, and press start. When the Instant Pot beeps indicating the cooking cycle is complete, press “Cancel” and allow the steam to pressure release naturally. This natural release may take 5-10 minutes.",
        "stepFour": "Once the pressure has released from the Instant Pot, open the lid and carefully transfer the turkey breasts from the trivet to a cutting board or serving platter. Carve the turkey breasts as desired, and serve"
      }],
      "prepTime": "50 minutes"
    },
    {
      "dishName":"Turkey Power Snack",
      "imgUrl": "https://lh3.googleusercontent.com/RI_LjbVzWTc6l3szz8xPfK87yjYtIM1mAl0CvGfWTEZUjraODIkQjG9a1gouMVC3rotnUBj48uQjVT6pWaU-=s640-c-rw-v1-e365",
      "briefDescription": "Easy and healthy delicious snack! Get your protein in!",
      "starRating": "4",
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Lbs",
        "oneName": "Ground Turkey",
        "twoAmount": "1/2",
        "twoUnit": "Cup",
        "twoName": "Yellow Onion",
        "threeAmount": "1/4",
        "threeUnit": "Cup",
        "threeName": "Red Pepper",
        "fourAmount": "2",
        "fourUnit": "Tbsp",
        "fourName": "Fresh Mint",
        "fiveAmount": "2",
        "fiveUnit": "Tbsp",
        "fiveName": "Red Curry Paste",
        "sixAmount": "1",
        "sixUnit": "Tsp",
        "sixName": "Ground Cumin",
        "sevenAmount": "1 1/2",
        "sevenUnit": "Tsp",
        "sevenName": "Coriander"
      }],
      "instructions": [{
        "stepOne": "Preheat the oven to 350 F and lightly grease casserole pan with olive oil.",
        "stepTwo": "Combine all ingredients in a large bowl, shape into 20 meatballs and place in the prepared pan.",
        "stepThree": "Salt and pepper to taste.",
        "stepFour": "Bake for 25 minutes or until cooked through. Enjoy!"
      }],
      "prepTime": "25 mins"
    }, {
      "dishName": "Turkey Sliders",
      "imgUrl": "https://lh3.googleusercontent.com/x0_VjiECkXmZ8PJSHbuqiUhhphIBK17go0wi-e3du5kGPDgg_mSglPF19iR6kRrO615hJP8WPjB5qk5_obDP=s640-c-rw-v1-e365",
      "briefDescription": "Yummy fan favorite.",
      "starRating": 4,
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Package",
        "oneName": "Hawaiian Roll",
        "twoAmount": "3/4",
        "twoUnit": "Cup",
        "twoName": "Honey Mustard",
        "threeAmount": "1/2",
        "threeUnit": "Cup",
        "threeName": "Mayonnaise",
        "fourAmount": "6",
        "fourUnit": "Slices",
        "fourName": "Swiss Cheese",
        "fiveAmount": "9",
        "fiveUnit": "Oz",
        "fiveName": "Smoked Turkey",
        "sixAmount": "4",
        "sixUnit": "Tbsp",
        "sixName": "Butter"
      }],
      "instructions": [{
        "stepOne": "Preheat the oven to 350°F. Cut the rolls lengthwise so you have two big pieces.",
        "stepTwo": "Spread 1/4 cup mustard and mayonnaise on each side of the rolls. Place the bottom roll in a pan, top with half of the turkey, Swiss cheese and the rest of the turkey. Place the other half of the rolls on top.",
        "stepThree": "Mix butter and 1/4 cup remaining mustard. Brush it on the rolls. Bake in the oven for 15 minutes until the cheese is melted.",
        "stepFour": "Serve warm."
      }],
      "prepTime": "25 mins"
    }, {
      "dishName": "Perfect Turkey Gravy",
      "imgUrl": "https://lh3.googleusercontent.com/hOBZGGApDzfIbztL4pMIW7qy-OUuSetLCBlnV2C1G1OUnmES7zYebLz6eMsnR7cWfjuiLIcOq8Saly7uQ6jxrw=s640-c-rw-v1-e365",
      "briefDescription": "Perfect gravy!",
      "starRating": 4,
      "ingredients": [{
        "oneAmount": "4",
        "oneUnit": "Cups",
        "oneName": "Turkey Drippings",
        "twoAmount": "1/2",
        "twoUnit": "Cup",
        "twoName": "Butter",
        "threeAmount": "1/2",
        "threeUnit": "Cup",
        "threeName": "All-purpose Flour",
        "fourAmount": "1",
        "fourUnit": "Tsp",
        "fourName": "Salt",
        "fiveAmount": "1",
        "fiveUnit": "Tsp",
        "fiveName": "Ground Pepper",
      }],
      "instructions": [{
        "stepOne": "If you’re using turkey drippings, pour them through a fine-mesh strainer to remove any debris. Allow strained drippings to cool a bit and spoon off any fat that has risen to the top.",
        "stepTwo": "If drippings don’t equal 4 cups of liquid, add chicken/turkey stock until you have 4 cups total.",
        "stepThree": "In a medium saucepan, melt the butter over medium-low heat. Once melted, whisk in flour and cook 2 minutes, stirring constantly.",
        "stepFour": "Slowly pour in turkey drippings or stock, stirring constantly. Continue cooking until gravy thickens, about 10 minutes. Season with salt and pepper. Serve immediately, or keep warm until ready to use. Enjoy!"
      }],
      "prepTime": "15 minutes"
    }, {
      "dishName": "Turkey Meatballs",
      "imgUrl": "https://lh3.googleusercontent.com/ClP10TMtLvaNw23Gg1csBBje9CrBXB868vsvWPPc9MsfkD6I-3ftwYKvHwRNehRnbWQ8fWHpGb3TIiJK4FyV=s640-c-rw-v1-e365",
      "briefDescription": "Comfort food at its finest.",
      "starRating": 5,
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": " ",
        "oneName": "Small Yellow Onion",
        "twoAmount": "1",
        "twoUnit": " ",
        "twoName": "Bell Pepper",
        "threeAmount": "1/3",
        "threeUnit": "Cup",
        "threeName": "Almond Flour",
        "fourAmount": "1",
        "fourUnit": "Tsp",
        "fourName": "Garlic Powder",
        "fiveAmount": "1/2",
        "fiveUnit": "Tsp",
        "fiveName": "Salt",
        "sixAmount": "1",
        "sixUnit": "Lbs",
        "sixName": "Ground Turkey",
        "sevenAmount": "2",
        "sevenUnit": "Tbsp",
        "sevenName": "Olive Oil"
      }],
      "instructions": [{
        "stepOne": "Preheat the oven to 400F. In a large bowl, stir together the onion, bell pepper, flour, garlic powder, and salt. Add the turkey and stir again until all the ingredients are well incorporated, being careful not to over mix.",
        "stepTwo": "Pour 1 tablespoon olive oil onto a sheet pan or large baking dish. Rub it around until the pan is well coated.",
        "stepThree": "Spoon 1 tablespoon of turkey mixture into your hands, rolling the mixture gently into a ball. Place the meatball onto the oiled pan, then continue the process with the remaining mixture. Edited to add: Depending on the texture of the ground turkey you use, the mixture may be on the wet side. If it’s too wet to roll, use a spoon or small ice cream scoop to scoop balls onto the pan.",
        "stepFour": "Drizzle the additional 1 tablespoon olive oil over the meatballs, rolling them around so they are well coated. Bake for 20 minutes, or until golden brown and cooked through, flipping once halfway through"
      }],
      "prepTime": "40 minutes"
    }, {
      "dishName": "Easy Leftover Turkey Stroganoff",
      "imgUrl": "https://lh3.googleusercontent.com/eJg0g8AI1IXOFJlE5gNOdlq0He7VIHVNcuD8dES8Doeg1F1MpHneau05VS7GRHUjMSvB5KF4O8RLbA-MtfITWw=s640-c-rw-v1-e365",
      "briefDescription": "Post-Thanksgiving Turkey leftovers put to good use!",
      "starRating": 3,
      "ingredients": [{
        "oneAmount": "1",
        "oneUnit": "Clove",
        "oneName": "Minced Garlic",
        "twoAmount": "3",
        "twoUnit": "Tbsp",
        "twoName": "Olive Oil",
        "threeAmount": "1",
        "threeUnit": "Cup",
        "threeName": "Sliced Mushrooms",
        "fourAmount": "3",
        "fourUnit": "Cups",
        "fourName": "Turkey Gravey",
        "fiveAmount": "1",
        "fiveUnit": "Tbsp",
        "fiveName": "Summer Savoury",
        "sixAmount": "1",
        "sixUnit": "Tsp",
        "sixName": "Black Pepper",
        "sevenAmount": "1/2",
        "sevenUnit": "Cup",
        "sevenName": "Sour Cream",
        "eightAmount": "4",
        "eightUnit": "Cups",
        "eightName": "Roasted Turkey"
      }],
      "instructions": [{
        "stepOne": "Begin by sautéing the garlic and mushrooms in the olive oil for several minutes until the mushrooms begin to get some good colour.",
        "stepTwo": "Add the other ingredients except the turkey and simmer for only about 5 minutes.",
        "stepThree": "Add the leftover turkey and continuing to simmer until the turkey is well heated.",
        "stepFour": "Serve over egg noodles."
      }],
      "prepTime": "30 minutes"
    }
  ]

  await Recipe.insertMany(recipes)
  console.log("Created recipes!")
}
const run = async () => {
  await main()
  db.close()
}

run()